$font = Hack Nerd Font

$base = rgb(30,30,46)
$mantle = rgb(24,24,37)
$surface0 = rgb(49,50,68)
$surface1 = rgb(69,71,90)
$text = rgb(205,214,244)
$subtext0 = rgb(166,173,200)
$subtext1 = rgb(186,194,222)
$mauve = rgb(203,166,247)
$blue = rgb(137,180,250)
$green = rgb(166,227,161)
$red = rgb(243,139,168)
$peach = rgb(250,179,135)

# GENERAL
general {
    hide_cursor = false
    ignore_empty_input = true
}

background {
    monitor = eDP-1
    path = screenshot
    color = rgba(0,0,0,1.0)
    blur_passes = 3
    brightness = 0.32
    blur_size = 8
    crossfade_time = 0.6
}

background {
    monitor = DP-3
    path = screenshot
    color = rgba(0,0,0,1.0)
    blur_passes = 3
    brightness = 0.32
    blur_size = 8
    crossfade_time = 0.6
}

# TIME
label {
  monitor = DP-3
  text = $TIME
  color = $text
  font_size = 96
  font_family = $font
  position = 0, -150
  halign = center
  valign = top
}

# DATE
label {
  monitor = DP-3
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $subtext1
  font_size = 20
  font_family = $font
  position = 0, -325
  halign = center
  valign = top
}

# USER AVATAR
image {
  monitor = DP-3
  text = $USER
  path = $HOME/Pictures/avatar.jpg
  size = 104
  rounding = -1
  border_size = 3
  border_color = $mauve
  position = 0, 75
  halign = center
  valign = center
}

input-field {
    size = 220, 48
    outline_thickness = 2
    dots_size = 0.35
    dots_spaceing = 0.2
    inner_color = rgba(30, 30, 46, 0.72)
    outer_color = $surface1
    check_color = $mauve
    fail_color = $red

    fail_text = 

    font_color = $text
    fade_on_empty = true
    rounding = 16

    placeholder_text = 󰌾
    placeholder_color = $subtext0

    position = 0, -20
    halign = center
    valign = center
}
