#!/usr/bin/env sh

if csrutil status | grep -q 'disabled'; then
    yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
    sudo yabai --load-sa
fi

# global settings
yabai -m config \
    external_bar off:40:0 \
    menubar_opacity 1.0 \
    mouse_follows_focus on \
    focus_follows_mouse autoraise \
    display_arrangement_order default \
    window_origin_display default \
    window_placement second_child \
    window_insertion_point focused \
    window_zoom_persist on \
    window_shadow on \
    window_animation_duration 0.0 \
    window_animation_easing ease_in_out_quint \
    window_opacity_duration 0.0 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.90 \
    window_opacity off \
    insert_feedback_color 0xffd75f5f \
    split_ratio 0.50 \
    split_type auto \
    auto_balance off \
    top_padding 8 \
    bottom_padding 8 \
    left_padding 10 \
    right_padding 10 \
    window_gap 12 \
    layout bsp \
    mouse_modifier cmd \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap

yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="小米互联服务" manage=off

yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus recent &> /dev/null"

# JankyBorder settings, 用来给窗口加边框
# https://github.com/FelixKratz/JankyBorders/wiki/Man-Page
borders active_color=0xff5ac8fa inactive_color=0xff3c3c3c width=5.0 hidpi=on &

echo "yabai configuration loaded.."
