# BEGIN_KITTY_FONTS
font_family      family='Victor Mono' postscript_name=VictorMono-Regular
bold_font        family='Victor Mono' style='Bold Oblique'
italic_font      family='Victor Mono' style='Medium Italic'
bold_italic_font family='Victor Mono' style='Bold Italic'
# END_KITTY_FONTS
