$base = rgb({{colors.surface.dark.hex_stripped}})
$mantle = rgb({{colors.surface_container_lowest.dark.hex_stripped}})
$surface0 = rgb({{colors.surface_container.dark.hex_stripped}})
$surface1 = rgb({{colors.outline_variant.dark.hex_stripped}})
$text = rgb({{colors.on_surface.dark.hex_stripped}})
$subtext0 = rgb({{colors.on_surface_variant.dark.hex_stripped}})
$subtext1 = rgb({{colors.on_surface_variant.dark.hex_stripped}})
$mauve = rgb({{colors.primary.dark.hex_stripped}})
$blue = rgb({{colors.secondary.dark.hex_stripped}})
$green = rgb({{colors.success.dark.hex_stripped}})
$red = rgb({{colors.error.dark.hex_stripped}})
$peach = rgb({{colors.warning.dark.hex_stripped}})
$input_background = rgba({{colors.surface_container.dark.hex_stripped}}b8)
