# BEGIN_KITTY_FONTS
font_family      family='VictorMono Nerd Font Mono' postscript_name=VictorMonoNFM-Regular
bold_font        family='VictorMono Nerd Font Mono' postscript_name=VictorMonoNFM-SemiBold features=calt
italic_font      auto
bold_italic_font family='VictorMono Nerd Font Mono' features=+calt
# END_KITTY_FONTS
