local M = {}

--- Personal syntax distinctions and integrations beyond Tokyo Night's defaults.
---@param c table<string, string> Disco palette
---@param accent string UI accent color
---@return table<string, vim.api.keyset.highlight>
function M.get(c, accent)
  local groups = {
    NormalFloat = { fg = c.text, bg = c.mantle },
    FloatBorder = { fg = c.overlay0, bg = c.mantle },
    FloatTitle = { fg = accent, bg = c.mantle, bold = true },
    WinSeparator = { fg = c.surface2 },
    CursorLine = { bg = c.surface0 },
    CursorLineNr = { fg = accent, bold = true },
    LineNr = { fg = c.overlay0 },
    Visual = { bg = c.surface1 },
    Search = { fg = c.text, bg = c.surface2 },
    IncSearch = { fg = c.crust, bg = accent, bold = true },
    CurSearch = { link = "IncSearch" },
    MatchParen = { fg = accent, bg = c.surface1, bold = true },
    Directory = { fg = c.sapphire },
    Title = { fg = accent, bold = true },
    Pmenu = { fg = c.text, bg = c.mantle },
    PmenuSel = { bg = c.surface1, bold = true },
    PmenuExtra = { fg = c.subtext0 },
    Bold = { fg = c.text, bold = true },
    DiagnosticOk = { fg = c.green },
    Added = { fg = c.green },
    Changed = { fg = c.sapphire },
    Removed = { fg = c.red },

    Function = { fg = c.peach, italic = true, bold = true },
    Keyword = { fg = c.mauve, italic = true, bold = true },
    String = { fg = c.green, italic = true },
    Constant = { fg = c.yellow, italic = true, bold = true },
    Type = { fg = c.sapphire, italic = true },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@constructor"] = { fg = c.lavender },
    ["@function"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.import"] = { fg = c.red, italic = true },
    ["@keyword.import.rust"] = { link = "@keyword" },
    ["@string"] = { link = "String" },
    ["@constant"] = { link = "Constant" },
    ["@module"] = { fg = c.red, italic = true },
    ["@namespace.builtin"] = { link = "@variable.builtin" },
    ["@property"] = { fg = c.teal },
    ["@variable.member"] = { link = "@property" },
    ["@variable.parameter"] = { fg = c.rosewater, italic = true },
    ["@punctuation.delimiter"] = { fg = c.sky },
    ["@spell"] = { italic = true },

    -- Keep Rust structs plain and enums emphatic, including LSP semantic tokens.
    ["@lsp.type.struct.rust"] = { fg = c.sapphire, italic = false, bold = false },
    ["@lsp.type.enum.rust"] = { fg = c.teal, italic = true, bold = true },
    ["@tag.builtin.vue"] = { fg = c.blue },
    ["@tag.vue"] = { fg = c.red },
    ["@lsp.type.component.vue"] = { fg = c.red },
    ["@tag.template.vue"] = { fg = c.mauve, bold = true },
    ["@tag.script.vue"] = { fg = c.yellow, bold = true },
    ["@tag.style.vue"] = { fg = c.green, bold = true },

    BlinkCmpSource = { fg = c.subtext0, italic = true, bold = true },
    BlinkCmpLabelMatch = { fg = accent, bold = true },
    BlinkCmpMenuSelection = { bg = c.surface1, bold = true },
    TelescopeMatching = { fg = accent, bold = true },
    TelescopeSelection = { bg = c.surface0, bold = true },
    TelescopePromptPrefix = { fg = accent },
    TelescopeBorder = { link = "FloatBorder" },
    TelescopePromptBorder = { link = "FloatBorder" },
    TelescopeResultsBorder = { link = "FloatBorder" },
    TelescopePreviewBorder = { link = "FloatBorder" },
    TelescopeTitle = { link = "FloatTitle" },
    FzfLuaBorder = { link = "FloatBorder" },
    FzfLuaHeaderBind = { fg = c.mauve },
    FzfLuaHeaderText = { fg = c.subtext1 },
    FzfLuaTitle = { link = "FloatTitle" },
    SnacksDashboardHeader = { fg = accent },
    SnacksDashboardKey = { fg = c.yellow, bold = true },
    SnacksPickerMatch = { fg = accent, bold = true },
    SnacksPickerPrompt = { fg = accent },
    SnacksPickerDirectory = { fg = c.subtext0 },
    SnacksIndent = { fg = c.surface1 },
    SnacksIndentScope = { fg = c.overlay1 },
    SnacksIndentChunk = { fg = accent },
    NoiceCmdlineIcon = { fg = accent },
    NoiceCmdlinePopupBorder = { link = "FloatBorder" },
    WhichKey = { fg = accent },
    WhichKeyGroup = { fg = c.sapphire },
    WhichKeyDesc = { fg = c.subtext1 },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { fg = c.yellow, bg = c.mantle },
    MiniFilesTitleFocused = { fg = accent, bg = c.mantle, bold = true },
    TreesitterContext = { bg = c.mantle },
    TreesitterContextLineNumber = { fg = c.overlay1, bg = c.mantle },
    TreesitterContextBottom = { sp = c.surface2, underline = true },
    UfoFoldedEllipsis = { fg = accent, italic = true },
    BqfSign = { fg = accent },
    BqfPreviewFloat = { link = "NormalFloat" },
    BqfPreviewBorder = { link = "FloatBorder" },
    BlinkCmpLabelDescription = { fg = c.subtext0 },
    BlinkCmpLabelDetail = { fg = c.subtext0 },
    BlinkCmpScrollBarThumb = { bg = c.surface2 },
    BlinkCmpScrollBarGutter = { bg = c.mantle },
    UfoFoldedFg = { fg = c.subtext1 },
    UfoFoldedBg = { bg = c.surface0 },
    DropBarMenuNormalFloat = { link = "NormalFloat" },
    DropBarMenuFloatBorder = { link = "FloatBorder" },
    DropBarMenuHoverEntry = { link = "Visual" },
    DropBarIconUISeparator = { fg = c.overlay1 },
    YankyYanked = { link = "IncSearch" },
    YankyPut = { link = "Visual" },
    CratesNvimPopupPillText = { fg = c.subtext1, bg = c.surface0 },
    CratesNvimPopupPillBorder = { fg = c.surface0 },
    CratesNvimPopupEnabled = { fg = c.green },
    CratesNvimPopupTransitive = { fg = c.sapphire },
    CsvViewHeaderLine = { fg = accent, bg = c.surface0, bold = true },
    CsvViewDelimiter = { fg = c.overlay1 },
    CsvViewComment = { link = "Comment" },
    LogGreen = { link = "DiagnosticOk" },
    LogBlue = { link = "DiagnosticInfo" },
    LogLvDebug = { link = "Comment" },
    LogLvTrace = { link = "Comment" },
    LogLvBacktrace = { link = "Comment" },
    LogLvVerbose = { link = "Comment" },
    GitSignsUpdate = { link = "GitSignsChange" },
  }

  local column_colors = { c.text, c.peach, c.sapphire, c.green, c.mauve, c.teal, c.yellow, c.pink, c.sky }
  for i, color in ipairs(column_colors) do
    groups["CsvViewCol" .. (i - 1)] = { fg = color }
  end

  return groups
end

return M
